[package]
name = "da-boot-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.21.3"
proc-macro2 = "1.0.101"
quote = "1.0.41"
syn = "2.0.106"
derive_more = { workspace = true }
derive-ctor = "1.0.6"
