[package]
name = "brom"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
simpleport = { workspace = true }
da-protocol = { path = "../../crates/da-protocol" }
interceptor = { path = "../interceptor" }
derive-ctor = { workspace = true }
