[package]
name = "da-boot"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
clap-num = { workspace = true }
colored = "3.0.0"
serialport = "4.7.3"
thiserror = { workspace = true }
derive_more = { workspace = true }
da-boot-macros = { path = "../da-boot-macros" }
