[package]
name = "da-port"
version = "0.1.0"
edition = "2024"

[features]
std = ["thiserror/std", "serialport"]

[dependencies]
thiserror = { version = "2.0.16", default-features = false }
serialport = { workspace = true, optional = true}
