[build]
target = "armv7a-none-eabi.json"

[target.'cfg(target_arch = "arm")']
rustflags = [
  "-C", "relocation-model=pic",
  "-C", "link-arg=-pie",
  "-C", "link-arg=-Bstatic",
  "-C", "link-arg=--no-dynamic-linker",
  "-C", "lto=fat",
  "-C", "codegen-units=1",
  "-C", "panic=abort",
]
